# Generated by Django 2.0.6 on 2018-07-08 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(verbose_name='Комментарий')),
            ],
            options={
                'db_table': 'Comment',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Video_URL', models.TextField(default='https://youtube.com/embed/')),
                ('Video_title', models.CharField(default='', max_length=200)),
                ('Video_o', models.TextField(default='')),
                ('Video_like', models.IntegerField(default=0)),
                ('Video_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'Video',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_video',
            field=models.ForeignKey(on_delete=True, to='fanvideo.Video'),
        ),
    ]
