# Generated by Django 2.0.6 on 2018-07-17 10:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fanvideo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 7, 17, 10, 20, 32, 181429, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
